### ISSUE TITLE
Source Training for Team

### ISSUE THREAD

**Issue by lydia-wu** [lydia-wu/cadence#11]
Tasking DUE: `Friday 2021-10-08 @12PM-EDT`
Time box: `45 minutes`

`Purpose`: to jumpstart team members into exploring the technologies we are utilizing to build our tools for the client
`Timing rationale`: try to have this done by Friday at noon so that we can start to create tasking for training on Friday after our recurring meeting

`Parameters`:
- resource must be free to us: `LinkedIn Learning`, `google scholar`, `MS Learning Suite`, etc.
- resource must be directly related to `PowerBI` or `ELK Stack`
- resource must be measurable: `a video series`, `a lab series`, etc.

`Deliverables`:
- [x] 1 or 2 training resources for PowerBI
- [x] 1 or 2 training resources for ELK Stack
- [x] 1 or 2 training data sets (if the above don't come with training sets built in)

**Comment by htyuki** [comment]
**PowerBI Training Resource:**
**_Microsoft Learning Training Courses: https://docs.microsoft.com/en-us/learn/powerplatform/power-bi?WT.mc_id=powerbi_landingpage-marketing-page_**
Specific Beginner Trainings:
Introduction to PowerBI (45 minutes): https://docs.microsoft.com/en-us/learn/modules/introduction-power-bi/1-introduction
Consume Data with PowerBI (2 hours): https://docs.microsoft.com/en-us/learn/paths/consume-data-with-power-bi/
Create and use analytics reports with PowerBI (6 hours): https://docs.microsoft.com/en-us/learn/paths/create-use-analytics-reports-power-bi/

**Comment by htyuki** [comment]
**ELK Stack Trainings**
_**Elastic Free Training**_
ELK Stack Quick Starts: https://www.elastic.co/training/free#quick-starts
ELK Stack Fundamentals: https://www.elastic.co/training/free#fundamentals
_**Official Elastic Community Training**_
Beginner's Crash Course of ELK Stack (6 hours): https://www.youtube.com/playlist?list=PL_mJOmq4zsHZYAyK606y7wjQtC0aoE6Es
Mini Beginner's Crash Course of ELK Stack (2 hours): https://www.youtube.com/playlist?list=PL_mJOmq4zsHbcdoeAwNWuhEWwDARMMBta
_**LinkedIn Learning **_ (one month free)
Learning the Elastic Stack: https://www.linkedin.com/learning/learning-the-elastic-stack-2?replacementOf=learning-the-elastic-stack-2018&src=go-pa&veh=sem_src.go-pa_c.LLS-C_NAMER_US_T1_EN_SEM_SEM_GoogleAds_NA_All_NA_NA_Core_NA_Dev-Sql-MKAG-tCPAFawkes_Nonbrand_Exact_pkw._pmt.b_pcrid.473973899404_pdv.c_plc._trgid.dsa-923242334522_net.g_learning&trk=sem_src.go-pa_c.LLS-C_NAMER_US_T1_EN_SEM_SEM_GoogleAds_NA_All_NA_NA_Core_NA_Dev-Sql-MKAG-tCPAFawkes_Nonbrand_Exact_pkw._pmt.b_pcrid.473973899404_pdv.c_plc._trgid.dsa-923242334522_net.g_learning&mcid=6841886150127296673&cname=&camid=11414361530&asid=110361572823&targetid=dsa-923242334522&crid=473973899404&placement=&dev=c&ends=1&gclid=CjwKCAjwtfqKBhBoEiwAZuesiJG5Em5AcpRadmpcf-AoyfHy78IPjtefSUX0bmJiQ3Q-QuiAu_wUxxoCw6IQAvD_BwE&gclsrc=aw.ds

**Comment by htyuki** [comment]
_**Training Datasets**_
_correct me if I got this wrong_
Here is a link from Towards Data Science where they listed sample datasets for data science portfolios:
https://towardsdatascience.com/all-the-datasets-you-need-to-practice-data-science-skills-and-make-a-great-portfolio-74f2eb53b38a

**Comment by hunter-alloway** [comment]
Deliverables 1, 2, and 3 included in the attached documents. The ELK Stack document is a resource that team members can use including a background of ELK Stack which is very helpful to understand the framework of the program and how it works. The second document including Power BI includes a link to GitHub as well as tutorial Youtube video which walks the user through coding implementation for ingesting data and understanding how ELK stack ingests these files. The second Youtube video illustrates how data can be manipulated in PowerBI from an excel file.

[ENGR481-ELK Stack Deep Dive.docx](https://github.com/lydia-wu/cadence/files/7312844/ENGR481-ELK.Stack.Deep.Dive.docx)
[IOT Source Training-Team#3.docx](https://github.com/lydia-wu/cadence/files/7312845/IOT.Source.Training-Team.3.docx)
