### ISSUE TITLE
Solidify Architecture for DG 05

### ISSUE THREAD

**Issue by lydia-wu** [lydia-wu/cadence#13]
**Purpose**: to fulfill LU requirements and create a foundation for Cadence, solidify system ARCHITECTURE both in GENESYS and in GitHub for the team to understand and communicate at the official Decision Gate meeting

tasking final due date: `2021-11-02, 08:00PM-EDT`
Timebox: `10 hours` / person

**DG prep** tasking (@michaeld3951):
- [x] schedule a preliminary DG05 meeting with Dr. Bae for `Wednesday 2021-11-03 @12PM EDT`
- [x] schedule the official DG05 meeting with Dr. Bae and client for `Friday 2021-11-05 @12PM EDT`

**DG final submission** tasking (congruent with #12, #9, #8, and #5 ):
- [x] finalize `visio` @lydia-wu 
- [x] document `visio` into `GENESYS` @hunter-alloway @michaeld3951 
- [x] generate preliminary meeting PPT @lydia-wu 
- [x] modify PPT after prelim comments from Dr. Bae and team @lydia-wu 
- [x] author `Architectural Domain Report Summary` + `Architecture Traceability Table` @michaeld3951
  - [x] table: `column 1 - Operations`, `column 2 - Power BI`, `column 3 - ELK Stack`
  - [x] `power bi` column: powerBI desktop, power query editor, dashboard display
  - [x] `ELK Stack` column : beats, logstash, elasticsearch, kibana 
- [ ] modify GENESYS as necessary and supply visuals for PPT @hunter-alloway
- [ ] compile and send all materials to professor and client 24 hours before presentation @lydia-wu

Additional tasking will appear here as we develop `achitecture` for our project.

**Comment by lydia-wu** [comment]
@michaeld3951 @htyuki @hunter-alloway 
Big steps coming up for this push to **DG-05**. If possible, I'd like to sync up with you before we go full-swing into next week. 

Can we sync up as a team on `2021-10-25 Monday, from 10:30-11:30am` via Discord? 

Tasking that I'll flesh out more in the meeting--
![image](https://user-images.githubusercontent.com/50425104/138389307-1a2d243f-b560-4096-b954-de46af9fa113.png)

**Comment by lydia-wu** [comment]
To get rid of some clutter, here is the tasking for operations, summarized (and due date updated)--

| Op. Num | Operation Architecture Name         | Lead | Support | Visio |
| ---------- | ------------------------------------- | ----- | --------- | ----- |
| 1 |  Learn the Customer's Current Landscape | @hunter-alloway | @michaeld3951 | ![](https://user-images.githubusercontent.com/50425104/138506600-d671d7d4-f68b-4fbc-b259-daf078f6bfdc.png) |
| 2 | Ingest Data                                                 | @michaeld3951 | @htyuki | ![](https://user-images.githubusercontent.com/50425104/138507885-e1a9b409-5ca2-4c31-954f-28c3b11f7c66.png) |
| 3 | Adapt Data to Tool                                     | @htyuki               | @lydia-wu | ![](https://user-images.githubusercontent.com/50425104/138508063-5f68137a-d990-440f-8699-69da3013a390.png) |
| 4 | Assess Data                                                | @lydia-wu           | @htyuki | ![](https://user-images.githubusercontent.com/50425104/138508298-8660997a-aa47-4f35-a8e0-92d768c9b2be.png) |
| 5 | Flag Data                                                    | @lydia-wu           | @hunter-alloway | ![](https://user-images.githubusercontent.com/50425104/138508359-0a8b5da8-b30a-4b79-9e42-ca2b64fabb26.png)  |
| 6 | Visualize Data                                             | @lydia-wu           | @michaeld3951 | ![](https://user-images.githubusercontent.com/50425104/138508835-cf72343c-bb08-433a-855c-3fad54d1d289.png) |

### Tasking Logistics
Tasking due date: `Monday, 2021-11-01 @10PM EDT`
Timebox: `3 hr`

### Tasking Description
- [ ] decide what mechanism(s) **Operation #** will require. Think in terms of `black boxes` with `inputs` and `outputs`
  - [ ] what software for what function(s)
  - [ ] what connecting points 
- [ ] estimate how much time each `black box` will take to build

### Tasking Deliverables
- [ ] compile findings in the working edit of the `Decision Gate 05` PPT (https://libertyuniv-my.sharepoint.com/:p:/g/personal/ljwu_liberty_edu/EUPo5_-IeYVLrXc3rO8WzcwBd26r78Z3cJnpC3cmIAg9BA?e=RhJn12)
- [ ] compile findings in the shared excel sheet (https://libertyuniv-my.sharepoint.com/:x:/g/personal/haalloway_liberty_edu/Eaf3KgW0BShDjoC0Nr98_cEB2LDsu3Bpa0QQjDa23TE1jA?e=H1jbi8)
- [ ] compile findings in a visual format (i.e.,`.visio` or `paint` or `word doc / excel`, etc.)

### Thought to keep in mind
- [ ] While the `lead` is responsible for this tasking, collaborate and learn from/with your `support` -- we are resources to one another
  - [ ] learn from `support` about his/her timing availability to receive asking
  - [ ] consider delegating some research/brainstorming/compilingFindings/etc to `support`
- [ ] `Decision Gate 06` is describing the guts of these `black boxes`; feel free to go ahead and be planning how you are going to flesh them out
- [ ] During this time, be training in `PowerBI` and/or `ELK Stack`, as we are going to start specializing people after next week
- [ ] keep a running thought on how you feel about this `Operation`, as you will probably become the point person for the `implementation phase`

**Comment by lydia-wu** [comment]
update on my end--I think I'm done with fleshing out the `PPT`/brainstorming for Op. 4-6 on a high level. Tomorrow, I will focus on trying to drill down some more details (with the mindset of heading toward the `implementation (DG06) phase`.  I may be putting together a `visio` that details what parts of `power query` / `logstash` / `etc.` that I hint at in the `.pptx`.

### In terms of the PPT moving forward:
Let me know your questions as you guys also flesh out the `PPT`. I'm not attached to a certain # of slides; if you think 1 is sufficient, that's cool. If you want to add additional slides, feel free. The vibe we may be going for this time around in the presentation is **"more visuals, fewer words" per slide, but definitely prepare a lot of words that verbally accompany each slide**. 

We are starting to actually _realize_ this concept of "Cadence", this idea of operations and functions and requirements that we've been throwing around.  `DG 06` will be another wordy presentation with lots of details, but this decision gate (05) I imagine will be just.. quite fun and colorful and hopeful.

**Comment by lydia-wu** [comment]
Also, to clarify on my expectations for the excel table for **architecture**--

As we work through building out **DG-05**, it's turning out that the nuance of our solution is going to fall much more on **DG-06** than **DG-05** since, as @michaeld3951 pointed out, one `platform/functionality` serves multiple `functions` (and even `operations`). 

With that in mind, feel free to forgo filling out the `.xlsx` file if it isn't valuable to your individual operations or brainstorming--it's purpose is to serve us, not the other way around. If it _is_ valuable to you completing **DG-05**, please use it--I still think that the `.xlsx` adds value when looking in the direction of **DG-06**, but probably it needs to be restructured to detail what we actually care about (_the current columns might not actually be useful. We'll continue to think about that as a team_).

**Comment by hunter-alloway** [comment]
Good morning @lydia-wu I have included my slides for Architecture #1 in the powerpoint presentation. Attached is both a pre-liminary questionarre for the the client to fill out as well as an interview (fill in the blank style) form that will help us modify system architecture to more closely align with the stakeholder requirements. I have also included the activity diagrams you wanted in the presentation for the functions domain to align with your original VISIO Diagram as a reference.


[Cadence Customer Analysis Interview-Understand Landscape.zip](https://github.com/lydia-wu/cadence/files/7454597/Cadence.Customer.Analysis.Interview-Understand.Landscape.zip)

**Comment by lydia-wu** [comment]
@hunter-alloway this is great! Thank you for your edits as well.

@htyuki @michaeld3951 how are things going? Are we on track for having DG-05 solidified for the prelim meeting by EOD todaY?

**Comment by hunter-alloway** [comment]
VISIO diagram uploaded and ready to go for tomorrow (architecture #1) @lydia-wu

**Comment by michaeld3951** [comment]
Here is the visio diagram for operation 2: 

[ELK Operation 2 Architecture.zip](https://github.com/lydia-wu/cadence/files/7470534/ELK.Operation.2.Architecture.zip)

**Comment by hunter-alloway** [comment]
Here is the visio diagram for operation 1:

[Operations 1 Architecture-VISIO.zip](https://github.com/lydia-wu/cadence/files/7470544/Operations.1.Architecture-VISIO.zip)

**Comment by lydia-wu** [comment]
@hunter-alloway @michaeld3951 @htyuki 
Here is the latest PPT deck and a combined visio

[cadence_visios_DG05.zip](https://github.com/lydia-wu/cadence/files/7475611/cadence_visios_DG05.zip)

[ENGR481_Team03_DG05 PPT.pdf](https://github.com/lydia-wu/cadence/files/7475613/ENGR481_Team03_DG05.pdf)

**Comment by lydia-wu** [comment]
@michaeld3951 @hunter-alloway once you drop the `GENESYS`, `trace table`, and `report` here, I'll submit to canvas

**Comment by michaeld3951** [comment]
Here's the write up for DG 05:

[SyAD-cadence.docx](https://github.com/lydia-wu/cadence/files/7479312/SyAD-cadence.docx)
[SyAD-cadence.pdf](https://github.com/lydia-wu/cadence/files/7479313/SyAD-cadence.pdf)

**Comment by michaeld3951** [comment]
Also, I added the traceability table to the shared excel file

**Comment by lydia-wu** [comment]
> Also, I added the traceability table to the shared excel file
@michaeld3951 can you format that into a PDF and drop it here?

**Comment by lydia-wu** [comment]
@hunter-alloway can you zip the latest GENESYSand drop it here (or email me the `.gnux` file directly)?

**Comment by hunter-alloway** [comment]
Most recent GENESYS file for Decision Gate 05


[ENGR481_Team03_Internet_of_Things (3).zip](https://github.com/lydia-wu/cadence/files/7489182/ENGR481_Team03_Internet_of_Things.3.zip)

**Comment by michaeld3951** [comment]
Here is the traceability table
[Op-Arch Mapping.pdf](https://github.com/lydia-wu/cadence/files/7489225/Op-Arch.Mapping.pdf)
[Op-Arch Mapping.xlsx](https://github.com/lydia-wu/cadence/files/7489226/Op-Arch.Mapping.xlsx)

**Comment by lydia-wu** [comment]
Woot! Thanks, team
![image](https://user-images.githubusercontent.com/50425104/140590557-e94db467-940d-44ea-9288-6e642030aa1e.png)

[ENGR481_SyAD_Team_03.zip](https://github.com/lydia-wu/cadence/files/7489386/ENGR481_SyAD_Team_03.zip)

**Comment by lydia-wu** [comment]
@hunter-alloway @michaeld3951 @htyuki 

Just a heads up--you can go ahead and check off all of these. woot!
![image](https://user-images.githubusercontent.com/50425104/140590645-224a9b68-db8d-401f-bf5c-36b29bce8ef6.png)
