### ISSUE TITLE
Solidify Detailed/Critical Design Review

### ISSUE THREAD

**Issue by hunter-alloway** [lydia-wu/cadence#19]
![image](https://user-images.githubusercontent.com/50425104/140591648-e06fd1e6-af9e-4099-8ff2-f8e2ee887320.png)
--Lj

**Comment by hunter-alloway** [comment]
I have created this issue in preperation for Decison Gate 06. @lydia-wu if you are already in the process of creating a new issue and have a template "in the works", please feel free to move across information in this issue to the one you have been working on.

Attached is the Design Defintion Record that I have been working on this evening. It connects both the Physical Requirements with the Design Components and although we have yet to come-up with components, the work I have done will enable us to cut and paste our findings to be completed in the weeks to come. I had time to work on this so I thought it'd be best to work now to save us time when final exams begin.

Keep up the great work on these Decision Gates. We're almost there. 

[ENGR481_System_Design_Definition_Record_Cadence_Team03.docx](https://github.com/lydia-wu/cadence/files/7465076/ENGR481_System_Design_Definition_Record_Cadence_Team03.docx)

**Comment by lydia-wu** [comment]
Attached is a revised file for the Design Definition Record from @hunter-alloway 

[ENGR481_System_Design_Definition_Record_Cadence_Team03.docx](https://github.com/lydia-wu/cadence/files/7477546/ENGR481_System_Design_Definition_Record_Cadence_Team03.docx)

Also, here are Visio diagrams--
[cadence_visios_DG05.zip](https://github.com/lydia-wu/cadence/files/7477553/cadence_visios_DG05.zip)

@hunter-alloway good thought for us to go ahead and be working on this; looks like a good chunk of information can be hashed out still, so I'm grateful for you bringing this to the top of the heap

**Comment by lydia-wu** [comment]
Let me know what else you need from me, and what support you need from the team (feel free to delegate to people to fill out different sections). @htyuki will be supporting me with some build details, so touch base with @michaeld3951 first for this side of building the report

**Comment by lydia-wu** [comment]
Tasking for Detailed/Critical Design Review:

- [ ] **PDF** of `Traceability Table` @htyuki 
  - [ ] it will probably be rather massive, but try your best to make it understandable in a PDF format
  - [ ] communicate that _everything in Architecture can be traced all the way back_ to requirements
  - [ ] communicate that _all requirements are satisfied_ (both system and stakeholder) 
- [ ] **GENESYS** SysML Database File @hunter-alloway 
- [ ] **PDF** of inputs and outputs of the System Design Definition Process `<already started>` @michaeld3951
  - [ ] build from @hunter-alloway's file ([here](https://github.com/lydia-wu/cadence/files/7477546/ENGR481_System_Design_Definition_Record_Cadence_Team03.docx))
- [ ] **PDF** of BOM @biosguy
  - [ ] columns: `name`/`quantity`/`price`/`source`/`rationale`
- [ ] A **zip** of any current experimental code/forms/etc. @lydia-wu 
  - [ ] all ELK Stack code
  - [ ] all PowerBI files
  - [ ] all forms, files, and active website reference links 
- [ ] **PPT** Deck @htyuki 
  - [ ] create a shell for us to fill in, then format and edit contents as necessary
  - [ ] slide(s) for traceability from end-to-end (requirements-to-architecture)
  - [ ] slide(s) for any new progress made 
  - [ ] slide(s) for "sneak peek" into `DG-06`
- [ ] **PDF** summary of System Design Definition Record @hunter-alloway 
  - [ ] capture succinct traceability table 
  - [ ] capture GENESYS highlights
    - [ ] screenshots of your day-to-day in the interface
    - [ ] a consolidation of all the diagrams/visuals you've created this semester
    - [ ] optional: a `metacognition` section about "things learned" or "mistakes made", etc.  
  - [ ] capture highlights from the `System Design Definition Process` PDF
  - [ ] capture highlights from `DG-05` and any sneak peeks you want to include from `DG-06`

**Comment by hunter-alloway** [comment]
@lydia-wu per your request, attached is a .pdf containing all the hierarchy visuals from GENESYS that we have used for our interim reports as well as for our decision gates.

[GENESYS Decision Gate Review-Hierarchy Visual.pdf](https://github.com/lydia-wu/cadence/files/7493339/GENESYS.Decision.Gate.Review-Hierarchy.Visual.pdf)

**Comment by lydia-wu** [comment]
@hunter-alloway 
- send an email to Dr. Bae
- options: (1) exempt from input/output reporting (2) substitute GENESYS "component" documentation with a visio/diagram/etc. of our 'components' (SQL files / database(s) / C files / kibana/P-BI dashboards) (3) a _vague_ GENESYS file

**Comment by hunter-alloway** [comment]
@lydia-wu I have not sent the email yet due to developments made during today's meeting which can be found under Cadence-> Meeting Notes->11/09/2021 More on this during tomorrow's meeting...

**Comment by lydia-wu** [comment]
Dr. Bae's email reference for the tasking in this issue:

(for the whole team) [ENGR481_SyDD_Team_xx.zip](https://github.com/lydia-wu/cadence/files/7514714/ENGR481_SyDD_Team_xx.zip)
(for the students) [ENGR481_Clarification_FA21.pdf](https://github.com/lydia-wu/cadence/files/7514715/ENGR481_Clarification_FA21.pdf)

@htyuki looks like there are two PDFs of traceability. One is as described above in tasking; the other is just putting all of our previous traceability tables into one PDF, no edits needed.

@biosguy the BOM excel can be found in the zip as well

**Comment by hunter-alloway** [comment]
Attached is an updated record of the Detailed Design Review Definition Record as well as two new GENESYS images that will aid with next weeks Decision Gate 6 presentation. Also attached is the latest revised GENESYS file for your records.

[ENGR481_System_Design_Definition_Record_Cadence_Team03 .docx](https://github.com/lydia-wu/cadence/files/7524927/ENGR481_System_Design_Definition_Record_Cadence_Team03.docx)

[Physical Architecture-Taglines.pdf](https://github.com/lydia-wu/cadence/files/7524928/Physical.Architecture-Taglines.pdf)
[Physical Architecture-Customer Interview.pdf](https://github.com/lydia-wu/cadence/files/7524929/Physical.Architecture-Customer.Interview.pdf)

[ENGR481_Team03_Internet_of_Things (6).zip](https://github.com/lydia-wu/cadence/files/7524935/ENGR481_Team03_Internet_of_Things.6.zip)

**Comment by hunter-alloway** [comment]
Hi everyone, attached is the link to the System Design Definition Record (SYDD) Word document for our submission on Tuesday.
Link: https://libertyuniv-my.sharepoint.com/:w:/g/personal/haalloway_liberty_edu/EWQe8oVz641NviLlMWFNkXgBqVEwCyFazqtwud0raBnYfg?e=pgboQX

**Comment by lydia-wu** [comment]
@michaeld3951 @htyuki @hunter-alloway 
PPT deck tentative layout for Critical Design Review--

| slide count | subject | lead for the slide |
| ------------ | -------- | ------------------ |
| 01-03 | introduction and table of contents | @michaeld3951 |
| 04-07 | current status of team; *very brief* recap of DG 1-5| @michaeld3951 |
| 08-12 | traceability (`could be table, could be a visual, could be a GIF -- super open to any way to communicate that everything in DG05 architecture can be traced all the way back to system/stakeholder requirements`) | @htyuki |
| 13-17 | recent progress (`>=1 slide for each of us`) ` @hunter-alloway this would be a great place to put your demo that you showed us in the meeting today! ` | _all team members_ |
| 18 | BOM | @biosguy |
| 19-20 | metacognition so far (`1/2 <= 1 slide for each of us`) | _all team members_ |
| 21-22 | sneak peek into DG06 | @lydia-wu |
| 23-24 | next steps (`timeline or table, whichever communicates the rest of the week/semester (Fall)`) and conclusion | @htyuki |

NOTE: **slides 08-18** are the most significant part of the presentation; we will spend the bulk of our time here

**Comment by htyuki** [comment]
Hey everyone, here is the sharepoint link to the PPT deck. 
https://libertyuniv-my.sharepoint.com/:p:/g/personal/htyukihiro_liberty_edu/ETr-0N-M-aZJrw4KozD_slcBwa2spmk7kRKPWpT62jx3pg?e=AthwYv

**Comment by lydia-wu** [comment]
@hunter-alloway I've updated the table (corresponding to `components` for operations 4-6); let me know what additional insight/rows I can provide for that section

**Comment by hunter-alloway** [comment]
Will do, thanks for your help @lydia-wu

**Comment by lydia-wu** [comment]
from @michaeld3951, for our records --
[ENGR481_BOM_Team_03.xlsx](https://github.com/lydia-wu/cadence/files/7543179/ENGR481_BOM_Team_03.xlsx)

**Comment by hunter-alloway** [comment]
Good evening Team, I have uploaded my section for tomorrow's powerpoint presentation. I have also included one more visual in the System Design Definition Record and do not have anything else to upload from GENESYS. (All/most fields are not aligned with the word document as well as input/output ports).

Seeing as the GENESYS file contains sensitive information taken from OneDrive, I will not be uploading the revised GENESYS files in OneDrive. Please go to: "Cadence->GENESYS->Revisions->November->11-15-2021" to access the revised GENESYS file. 

Attached is the revised .PDF document containing all of our visuals from GENESYS this semester.

[Decision Gate Hierarchy-Five Domain Analysis.pdf](https://github.com/lydia-wu/cadence/files/7543483/Decision.Gate.Hierarchy-Five.Domain.Analysis.pdf)

**Comment by htyuki** [comment]
Here are the attached Traceability Tables. One is the overview and the other are separate tables.
[TraceabilityOverview.pdf](https://github.com/lydia-wu/cadence/files/7545278/TraceabilityOverview.pdf)
[Traceability_Tables.pdf](https://github.com/lydia-wu/cadence/files/7545279/Traceability_Tables.pdf)

**Comment by lydia-wu** [comment]
The Detailed Design Record has been submitted:
![image](https://user-images.githubusercontent.com/50425104/142017608-bcc2a9c0-5608-45fd-9ba5-a01ae7e6d570.png)

Feel free to check off this box in your Canvas Dashboard:
![image](https://user-images.githubusercontent.com/50425104/142017708-dc039d52-2fdd-4457-a0a6-afc0ebfe82f4.png)

**Comment by lydia-wu** [comment]
The Critical Design Presentation has been submitted:
![image](https://user-images.githubusercontent.com/50425104/142018946-c1858d0d-4974-45bf-9343-e0e6132d86df.png)

Feel free to check off this box in your Canvas Dashboard:
![image](https://user-images.githubusercontent.com/50425104/142019118-cd5b3aa1-38aa-48e8-b22a-47636581e585.png)

Following today's meeting, this may need to be revised. This issue will stay open until approval is obtained from both the client and the professor at 2PM today.

**Comment by lydia-wu** [comment]
Looks like we're good to go for today! Woot!

Next steps:
- [ ] @biosguy sync up with Dr. Bae on `Dec. 1` on specifics of `ELK Stalk BOM`

here is the updated zip (updates: `BOM` and `Traceability Tables`):
[ENGR481_SyDD_Team_03.zip](https://github.com/lydia-wu/cadence/files/7549586/ENGR481_SyDD_Team_03.zip)

**Comment by lydia-wu** [comment]
![image](https://user-images.githubusercontent.com/50425104/142060573-e49fb633-78e5-4f50-9ba3-b58ad28fe177.png)
