### ISSUE TITLE
Solidify Implementation Strategy for DG 06

### ISSUE THREAD

**Issue by lydia-wu** [lydia-wu/cadence#20]
**Purpose**: to fulfill LU requirements and create a foundation for Cadence, solidify system IMPLEMENTATION PLAN both in GENESYS and in GitHub for the team to understand and communicate at the official Decision Gate meeting

tasking final due date: `2021-11-19, 08:00PM-EDT`
Timebox: `15 hours`

**DG prep** tasking (@michaeld3951):
- [x] schedule a preliminary DG06 meeting with Dr. Bae for `Wednesday 2021-11-03 @12PM EDT`
- [x] schedule the official DG06 meeting with Dr. Bae and client for `Friday 2021-11-05 @12PM EDT`

**DG prep** tasking @lydia-wu: [due date: `2021-11-16, 08:00PM-EDT`]
- [x] build `PPT` 
- [x] build `3S Documentation`
- [x] build `MS Project File`

**DG final submission** tasking (semi-congruent with #13, #12, #9, #8, and #5 ): [due date: `2021-11-18, 08:00PM-EDT`]
- [ ] modify `PPT` after prelim comments from Dr. Bae and team @michaeld3951 
- [x] modify `IpD` after prelim comments from Dr. Bae and team @hunter-alloway  
- [x] modify `MS Project File` after prelim comments from Dr. Bae and team @htyuki
- [ ] create `GENESYS` documentation @hunter-alloway 
- [x] create `Table of Implementation WBS PDF` @michaeld3951 
- [ ] compile and send all materials to professor and client 24 hours before presentation @lydia-wu

![image](https://user-images.githubusercontent.com/50425104/140591682-6e1a7fe2-02a5-4273-9722-99f916bea0e1.png)

**Comment by lydia-wu** [comment]
@michaeld3951 @htyuki @hunter-alloway As you play with your respective operations this next week, drop time estimates to me ASAP. They can be hazy quotes, but I'd like estimates of
- your technical availability per week
- an estimate of how many hours per week this build is going to take (including learning/researching how to do things) (for your respective operations)
- an estimate of how many hours per week of support you'll need on your respective operations

Consider a timeframe of:
1. `Mon Jan 10 - Fri April 15` our build phase, concluding with `Decision Gate 07` (_Integration and Verification_) (this is the Friday before a 3-day Easter weekend)
2. `Tue April 19 - Tue April 26` we live in a `Decision Gate 08` mindset (_Validation_) and prepare the `Poster Presentation`/`Final Report`

**Comment by hunter-alloway** [comment]
@lydia-wu per your request, attached is a .pdf containing all the hierarchy visuals from GENESYS that we have used for our interim reports as well as for our decision gates.

[GENESYS Decision Gate Review-Hierarchy Visual.pdf](https://github.com/lydia-wu/cadence/files/7493311/GENESYS.Decision.Gate.Review-Hierarchy.Visual.pdf)

**Comment by htyuki** [comment]
For the timeframe, here is what I am projecting for Operation 3:

Decision Gate 07 (Jan 10 - April 15)
Technical Availability Per Week: 8 hours
Hours per Week to Build: 8 hours
Support Hours per Week: 1-2 hours

Decision Gate 08 (April 19th - April 26)
Technical Availability Per Week: 8 hours
Hours per Week to Build: 6 hours
Support Hours per Week: 1 hour

**Comment by hunter-alloway** [comment]
**My Timeframe:** 
Decision Gate 07 (January throgh April)
Availability: Approximately 5-10 hoursn per week depending on how detailed the client information needs to be 
Hours per week for run time and variance de-bugging: 3 hours
Support Hours: 1 hour

Decision Gate 08
Availability: 8 hours per week
Build Time: 7 hours 
Support Per Week: 3 hours with a meeting discussing technical insight with Mr. Stansell

**Comment by michaeld3951** [comment]
Operation 2 Time Estimates:

DG 07:
Availability Per Week: 8 hours
Build Time Per Week: 8-10 hours
Support Per Week:  1-2 hours

DG 08:
Availability Per Week: 10 hours
Build Time Per Week: 5 hours
Support Per Week:  0-1 hour

**Comment by lydia-wu** [comment]
A link for reference; should be built out by Tue 5pm
https://libertyuniv-my.sharepoint.com/:p:/g/personal/ljwu_liberty_edu/ETUrIdrmrQVDmIujL4bntOsBhpzHyf_y85A0i_xVc1ySTQ?e=dfdbbe

**Comment by lydia-wu** [comment]
Here's a preview of our timeline for Spring 2022.  Will be releasing a high-level Gantt soon--
<img width="689" alt="CADENCE_Timeline_02" src="https://user-images.githubusercontent.com/50425104/142023696-aeb82424-433f-4257-8a9b-854c1c462c11.png">

**Comment by lydia-wu** [comment]
preview of the MS Project Gantt-
![image](https://user-images.githubusercontent.com/50425104/142088714-d4ffd9ae-9ceb-403e-b295-5b34a182b6ba.png)

**Comment by hunter-alloway** [comment]
@lydia-wu Attached is the VISIO file with the visualized 10000ft timeline per our discussion. I have tried to eliminate excess visuals for ease of comprehension. Please let me know how I can support you for tomorrow's pre-lim. I have attached the slide to the presentation.

[ENGR482_VISIO_Timeline.zip](https://github.com/lydia-wu/cadence/files/7552009/ENGR482_VISIO_Timeline.zip)

**Comment by lydia-wu** [comment]
The report should be good to go. Here is a .zip of all the files so far. Following today's prelim meeting, you can access the word doc and PPT from the links here (also listed above in this issue):

the DG-06 PPT
the DG-06 documentation

[ENGR482_IpD_Team_03.zip](https://github.com/lydia-wu/cadence/files/7556423/ENGR482_IpD_Team_03.zip)

**Comment by lydia-wu** [comment]
also, attached is the alternate visio --
[ENGR482_IpD_Team_03_Gantt_v2.zip](https://github.com/lydia-wu/cadence/files/7556468/ENGR482_IpD_Team_03_Gantt_v2.zip)

**Comment by lydia-wu** [comment]
<html xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=PowerPoint.Slide>
<meta name=Generator content="Microsoft PowerPoint 15">
<style>

</style>
</head>

<body>




Checkpoint | Estimated      End Date | Description
-- | -- | --
DG 07:        Integration Report   , Verification Report   , Verified System Prototype | Friday   2022-03-30 | How   did the build process go? Does the system meet stakeholder expectations? Does   the system exist?
Poster   Presentation | Thursday   2022-04-21 | What   has Cadence been up to since August 2021?
DG   08:       Validation Report   , Validated System Prototype | Friday   2022-04-15 | Does the system operate as   expected from architecture and schematic plans?




</body>

</html>

**Comment by lydia-wu** [comment]
Timeline should now be up to date--
![image](https://user-images.githubusercontent.com/50425104/142268314-9ba364ee-7b65-41b4-a533-c3592e0e64d1.png)

@michaeld3951 @hunter-alloway after you modify (from tasking in first comment of this issue), can you also drop a PDF of your respective documents into the issue?

**Comment by hunter-alloway** [comment]
No problem @lydia-wu

**Comment by hunter-alloway** [comment]
Hi @lydia-wu per Dr. Bae's reccomendations, I have revised the VISIO diagram for tomorrow's presentation and have included the new image to the slides.


[ENGR481_VISIO_Timeline.pdf](https://github.com/lydia-wu/cadence/files/7567000/ENGR481_VISIO_Timeline.pdf)

**Comment by michaeld3951** [comment]
Here are the pdfs for the implementation table and presentation slides

[Implementation Table.pdf](https://github.com/lydia-wu/cadence/files/7567310/Implementation.Table.pdf)

[DG06 Presentation.pdf](https://github.com/lydia-wu/cadence/files/7567309/DG06.Presentation.pdf)

**Comment by lydia-wu** [comment]
woot! implementation table looks good. updated VISIO timeline looks good.

waiting on--
@hunter-alloway latest GENESYS file
@htyuki `mpp` modifcations so that @michaeld3951 and @hunter-alloway can add the updated MS project images to the `PPT` and `report` respectively

**Comment by hunter-alloway** [comment]
@lydia-wu attached is the most recent GENESYS file. I have yet to update the documents and risk assessment fields as I just created the risk fields in our word document. This file should have adequate information to meet the requirements for Deicison Gate 06. 

[ENGR481_Team03_Internet_of_Things (5).zip](https://github.com/lydia-wu/cadence/files/7567854/ENGR481_Team03_Internet_of_Things.5.zip)

**Comment by htyuki** [comment]
@lydia-wu Sorry for the late submission but here is the updated Project file. Also, since the poster and report are outside the scope of build the Y-Architecture, I un-indented it to avoid errors. Let me know if that is alright or not.
[ENGR481_IpD_Team_03.mpp.zip](https://github.com/lydia-wu/cadence/files/7568317/ENGR481_IpD_Team_03.mpp.zip)

**Comment by michaeld3951** [comment]
updated powerpoint:
[DG06 Presentation.pdf](https://github.com/lydia-wu/cadence/files/7571356/DG06.Presentation.pdf)

**Comment by lydia-wu** [comment]
Team! Well done. Thanks for burning hot on this. Attached is the zip that will be submitted to canvas once Dr. Bae opens a link--

[ENGR482_IpD_Team_03.zip](https://github.com/lydia-wu/cadence/files/7572051/ENGR482_IpD_Team_03.zip)

Closing this issue now! Woot!!

**Comment by lydia-wu** [comment]
![image](https://user-images.githubusercontent.com/50425104/146256119-1e5d332a-4aeb-4251-a4fc-f244ab308d52.png)

**Comment by hunter-alloway** [comment]
Thanks for uploading this @lydia-wu Just went through what we submitted. I just want to confirm that we had this completed before the break, but never got around to submitting it as the submission attempt had not been created, is that correct?

**Comment by hunter-alloway** [comment]
Thank you @lydia-wu
