### ISSUE TITLE
Working Meeting for "Defining Normal"

### ISSUE THREAD

**Issue by lydia-wu** [lydia-wu/cadence#3]
**Purpose**: to flesh out what "normal" vocabulary we are going to use.
A tasks due: 2021-09-17, EOD

Tasking:
- [x] schedule a 60 minute "brainstorming" session with team and client to whiteboard terms and settle on a rough draft (can be scheduled for Friday this week or Monday/Tue of next week)
- [x] review "image A" below for some initial ideas. Come up with a few more terms if any of those don't match (for example, is there a better work for "communicates as expected" than `consistent`?
- [x] review "image A" below for some initial ideas. Come up with more cases if DICTIONARY=`consistent`/`semi-consistent`/`inconsistent`/`stillborn`' doesn't feel robust enough
- [x] review "image A" below for some initial ideas. What do you think of a "prefix/suffix" idea with `redeemed`/`declining`/`lost`? How can we tighten up that vocabulary? Maybe we need to move more abstract like assigning colors? Maybe shapes/numbers/objects instead of adjectives?

Image A:
![](https://cdn.discordapp.com/attachments/882746388704809000/887698278110625842/unknown.png)

**Comment by htyuki** [comment]
<img width="800" alt="Screen Shot 2021-09-17 at 12 11 06 AM" src="https://user-images.githubusercontent.com/75403138/133722914-32dfce4b-7382-49db-b999-687ac0f2392c.png">
<img width="1228" alt="Screen Shot 2021-09-17 at 12 11 16 AM" src="https://user-images.githubusercontent.com/75403138/133722922-96b5ba21-525c-4ee6-af77-5ee6b6379f7d.png">

**Comment by htyuki** [comment]
<img width="801" alt="Screen Shot 2021-09-17 at 12 12 47 AM" src="https://user-images.githubusercontent.com/75403138/133723040-8070338a-e0fd-47cb-b0a1-6906f331232e.png">

**Comment by htyuki** [comment]
<img width="1233" alt="Screen Shot 2021-09-17 at 12 13 48 AM" src="https://user-images.githubusercontent.com/75403138/133723088-04e173d2-6e6a-4f3f-ad54-2f6cce389cd4.png">

**Comment by lydia-wu** [comment]
Good work! looking forward to Monday. Thanks for scheduling
