### ISSUE TITLE
Op 1: Architecture Dev

### ISSUE THREAD

**Issue by lydia-wu** [lydia-wu/cadence#32]
`due 2022-01-21 12 PM ET`
`timebox: 30 min`

Develop an Architecture for HIGH-level roadmap of Operation 1 code; will review with @biosguy and team at standup.

**Comment by hunter-alloway** [comment]
### V.1.5 Architecture for Data Simulator

[Cadence-Data Simulator V.1 Architecture.pdf](https://github.com/lydia-wu/cadence/files/8034768/Cadence-Data.Simulator.V.1.Architecture.pdf)

**Comment by lydia-wu** [comment]
Closed with goals met
