### ISSUE TITLE
Solidify Requirements for DG 01

### ISSUE THREAD

**Issue by lydia-wu** [lydia-wu/cadence#5]
**Purpose**: to fulfill LU requirements _and_ create a foundation for Cadence, solidify system/stakeholder requirements both in GENESYS and in GitHub for the team to understand and communicate at the official Decision Gate meeting

tasking due date: 2021-09-17, 11:30AM

tasking
- [x] schedule working meeting between @hunter-alloway and @lydia-wu to flesh out requirements
- [x] author GENESYS @hunter-alloway 
- [x] author document/excel, then publish to GitHub @lydia-wu 
- [x] author PPT to communicate to "pre-DG meeting" with Dr. Bae on Friday @lydia-wu 
- [x] submit to client for review

**Comment by lydia-wu** [comment]
meeting @hunter-alloway 3:30-4pm EDT, 2021-09-15 via **Discord**

**Comment by lydia-wu** [comment]
@hunter-alloway  please fill out the highlighted columns (`Desc`, `Rationale`, `Origin`) in the file below. Send questions my way; attempt `Priority` if you have time, but don't feel pressure to get it perfect.

> Here are my response windows:
> > Thursday: 8AM-11AM
> > Friday: 10AM-11AM

[Cadence_requirements_draft.xlsx](https://github.com/lydia-wu/cadence/files/7173540/Cadence_requirements_draft.xlsx)

**Comment by lydia-wu** [comment]
meeting with client 4:30-6:10pm EDT, 2021-09-15 via **Teams**

**Comment by lydia-wu** [comment]
thanks @hunter-alloway . can you download this file (**draft_1_2**) and make a hierarchy diagrams from it? Will be a good visual for the decision gate

[Cadence_requirements_draft_1_2.xlsx](https://github.com/lydia-wu/cadence/files/7182257/Cadence_requirements_draft_1_2.xlsx)
e.

**Comment by lydia-wu** [comment]
@michaeld3951 @htyuki @hunter-alloway  Congruent with an email update I just sent, here are the current materials I plan to float by Dr. Bae tomorrow at our 12:05pm _preliminary DG01 meeting_. I'll lead the PPT, but I'll pull you guys in where it's relevant or you have some particular insight, so be ready to hop in. Let me know your questions or thoughts on any of the stuff below.

[Cadence_requirements_draft_1_2.xlsx](https://github.com/lydia-wu/cadence/files/7182269/Cadence_requirements_draft_1_2.xlsx)

[Cadence arch concept.pdf](https://github.com/lydia-wu/cadence/files/7182270/Cadence.arch.concept.pdf)

[engr481_team03_preliminaryDecisionGate01_20210917.pptx](https://github.com/lydia-wu/cadence/files/7182273/engr481_team03_preliminaryDecisionGate01_20210917.pptx)

**Comment by lydia-wu** [comment]
Following meeting with Dr. Bae today, tasking for Reqs moving forward, referring to this updated requirements sheet:
[Cadence_requirements_draft_2.xlsx](https://github.com/lydia-wu/cadence/files/7187204/Cadence_requirements_draft_2.xlsx)

| Assignee | Tasking |
| ----- | ----- |
| @htyuki |  go through and **map** each `system requirement` in this excel to a corresponding `stakeholder requirement` |
| @htyuki | go through the requirements; assign **priorities** to each requirement. Then confer with client for approval |
| @michaeld3951 | Author **paper report**; reference  @hunter-alloway's GENESYS work and @htyuki insight |
| @hunter-alloway | flesh out descriptions and remaining fields (sans "priority"), fill everything into **GENESYS**, generate revised Hierarchy Diagram |
| @lydia-wu | Put together PPT; schedule Friday DG 02, finalize with client |

**Comment by lydia-wu** [comment]
scheduled DG 02 for 2021-09-24 Friday @2:10PM-EDT

**Comment by michaeld3951** [comment]
[strs-cadence.docx](https://github.com/lydia-wu/cadence/files/7192730/strs-cadence.docx)

Here is the written report for DG 01 (draft). It is based off of the template that Dr. Bae provided in Canvas. 

I have questions pertaining to these sections:

Assumptions -- what assumptions do we have for this project?

References -- are there any other references that should be listed/edited?

Business Abstract -- do we need this section? Should we just lump the stakeholders sub-section into the  stakeholder requirements section since we only have 1 stakeholder?

Requirements -- should we upload a separate excel spreadsheet that just has the stakeholder requirements in it and not the system requirements as well?

**Comment by htyuki** [comment]
[Cadence_Requirements_Priority.xlsx](https://github.com/lydia-wu/cadence/files/7192959/Cadence_Requirements_Priority.xlsx)

I attached an excel file that:
1. Correlates the stakeholder requirements to the system requirements
2. Assign priorities to each requirement (currently under client review)

**Comment by lydia-wu** [comment]
@michaeld3951 thoughts below to flesh out the report:
> Assumptions -- what assumptions do we have for this project?  

(pulled this format from [here](https://projectbliss.net/project-assumptions-list/))
- **Resources**:
  - Utilized technologies (PowerBI and ELK Stack) will be accessible to the team, client, and customers
  - Team members and client will both allocate time each week
  - Dr. Bae, advising professor, will be available to the team as requested
- **Budget**
  - Project costs will stay the same as initially budgeted costs
  - Training will be conducted internally with no additional training costs incurred
- **Scope of Delivery**
  - The project scope will not change once the stakeholders sign off on the scope statement unless the team members, client, and advising professor *all* sign off on an requirement update
- **Schedule: tasks, durations, and dependencies needed to complete the project**
  - Tasking will be given with a reasonable amount of lead time for teammates to complete tasks
  - Tasking will be communicated well or fleshed out if not communicated well
  - Tasking will be dynamic as teammates express desire to scale up or scale down scope of task
- **Technology**
  - Team will be expected to code
  - The solution may use the existing test environment

> References -- are there any other references that should be listed/edited?

- Consider including the "public" and "private" documents (in the client's OneDrive) in `section 1.1.1`
- Consider including the PDFs that Dr. Bae sent regarding Req formatting (the two tables in that one email) in section 1.1.2

> Business Abstract -- do we need this section? Should we just lump the stakeholders sub-section into the stakeholder requirements section since we only have 1 stakeholder?

- This might be a good place, at least in `Section 1.2 & 1.3`, to put in the client's "Mission Statement", but formatted better for a doc. 
- For `Section 1.4`, the stakeholder is the client, the organization is "Essential IoT, LCC".  I don't think we should lump it together.  
- `Table 2-1` will be relatively small: two rows (LU and "E-IoT")-- the main interests for LU I assume are to (1) teach us how to work as a team, (2) build a professional relationship with E-Iot, and (3) build the reputation of LU by producing successful Capstone projects. The main interests for E-IoT are to (1) expand attractiveness of the company, (2) build a relationship with LU for future work, (3) mentor future Christian engineers. Reach out to Dr. Bae and/or the client if you find haziness on either of these. I think that that might be enough to work off of to flesh out the rest of the table.

> Requirements -- should we upload a separate excel spreadsheet that just has the stakeholder requirements in it and not the system requirements as well?
- Yes. Good call.

What are your thoughts? Let me know if I can re-word/flesh out/distill any of what I've just written up there^

**Comment by hunter-alloway** [comment]
Attached is an updated list of the System/Stakeholder requirements. I will have the description/rationale fields updated before our next meeting on Monday, September 20. The systesm requirements have been uploaded to GENESYS and the Stakeholder Requirements will be uploaded before tomorrow's meeting. 
[Cadence_Requirements_Priority (1).xlsx](https://github.com/lydia-wu/cadence/files/7193064/Cadence_Requirements_Priority.1.xlsx)

**Comment by michaeld3951** [comment]
[strs-cadence.docx](https://github.com/lydia-wu/cadence/files/7193303/strs-cadence.docx)

Here is an updated report for DG 01. Please review it and let me know what I should change

**Comment by hunter-alloway** [comment]
[Cadence_Requirements_Priority (1).xlsx](https://github.com/lydia-wu/cadence/files/7193354/Cadence_Requirements_Priority.1.xlsx)
Updated version of the stakeholder and system requirements. Note: All fields in system requirements are complete.

**Comment by hunter-alloway** [comment]
Updated version of the stakeholder and system requirements. Note: All fields in system and stakeholder requirements are complete.
[Cadence_Requirements_Updated_09-20-2021.xlsx](https://github.com/lydia-wu/cadence/files/7196887/Cadence_Requirements_Updated_09-20-2021.xlsx)

**Comment by lydia-wu** [comment]
Updated version of the stakeholder and system requirements.
Changes: adjusted numbering for clarity.

[Cadence_Requirements_v4.xlsx](https://github.com/lydia-wu/cadence/files/7197804/Cadence_Requirements_v4.xlsx)

@tyuki can you go through and re-map the system to the stakeholder requirements?
@hunter-alloway check to see if this aligns with the GENESYS you're working on

**Comment by lydia-wu** [comment]
Hey team--here is the PPT that I will be sending out in a couple hours in preparation for the Decision Gate tomorrow.  
notes--
1. In the "notes" section of the PPT are the assignments for who is taking which slide.
2. the meat of this presentation is in section "B"; @htyuki and @michaeld3951 the vision I have is that you'll elaborate on the requirements by _talking_ about `description` and `rationale`, but they won't be listed on the slides themselves (to improve slide readability).
3. @hunter-alloway you'll be on stand-by to summarize what @htyuki  and @michaeld3951  have said after each of their slides; details are in the "notes" section
4. @hunter-alloway once you've got those visuals, please drop them into the PPT where indicated (and adjust slide count as necessary)

Shoot me your questions as they arise!

(also attached for reference--the slide deck from the preliminary meeting last week)
[engr481_team03_preliminaryDecisionGate01_20210917.pptx](https://github.com/lydia-wu/cadence/files/7198085/engr481_team03_preliminaryDecisionGate01_20210917.pptx)

[ENGR481_Team03_DecisionGate01.pptx](https://github.com/lydia-wu/cadence/files/7198084/ENGR481_Team03_DecisionGate01.pptx)

**Comment by lydia-wu** [comment]
The latest on the materials for the DG01

1. GENESYS File <pending from @hunter-alloway>
2. [ENGR481_Team03_DecisionGate_01_STRS.docx](https://github.com/lydia-wu/cadence/files/7198203/ENGR481_Team03_DecisionGate_01_STRS.docx)
3. [ENGR481_Team03_DecisionGate_01.pptx](https://github.com/lydia-wu/cadence/files/7198204/ENGR481_Team03_DecisionGate_01.pptx) <pending review from team>
4. [ENGR481_Team03_DecisionGate_01_StakeholderRequirements.pdf](https://github.com/lydia-wu/cadence/files/7198205/ENGR481_Team03_DecisionGate_01_StakeholderRequirements.pdf)

Planning to submit to Canvas/etc. at 4:30PM-EDT today.

**Comment by hunter-alloway** [comment]
Attached are the revised System & Stakeholder requirements. I have created two sheets to seperate them for clarity per @lydia-wu reccomendation.
[Cadence_System&Stakeholder_Requirements.xlsx](https://github.com/lydia-wu/cadence/files/7212280/Cadence_System.Stakeholder_Requirements.xlsx)
