### ISSUE TITLE
Interim Report (recurring)

### ISSUE THREAD

**Issue by lydia-wu** [lydia-wu/cadence#7]
Please drop interim report files here from now on.
Reference for additional insight/tasking: https://github.com/lydia-wu/cadence/wiki/*-Recurring-Assignments-*-INTERIM-REPORT

**Comment by lydia-wu** [comment]
Latest:
1. Waiting on Technical Report from @htyuki 
2. @michaeld3951 consider updating the PPT to reflect the latest MS Project file in the zip below (minor changes/tasking added)

[ENGR481_IR_04_Team_03_incomplete.zip](https://github.com/lydia-wu/cadence/files/7193417/ENGR481_IR_04_Team_03_incomplete.zip)

@htyuki  @hunter-alloway @michaeld3951 please update your files in this "issue" from now on (instead of to the "code" section). Perhaps this will be less clunky than relying on Discord uploads.

**Comment by michaeld3951** [comment]
Below are the meeting minutes from the past week -- not a whole lot to report as we were finalizing everything for decision gate 2
[ENGR481_IR_05_Meeting_Minutes_01_Team_03.pdf](https://github.com/lydia-wu/cadence/files/7228223/ENGR481_IR_05_Meeting_Minutes_01_Team_03.pdf)
[ENGR481_IR_05_Meeting_Minutes_02_Team_03.pdf](https://github.com/lydia-wu/cadence/files/7228224/ENGR481_IR_05_Meeting_Minutes_02_Team_03.pdf)

**Comment by lydia-wu** [comment]
Below is the latest .mpp
@michaeld3951 @htyuki  there are quite a few additions to keep in mind for the PPT and Tech report:
[ENGR481_IR_05_Team_03_mmp.zip](https://github.com/lydia-wu/cadence/files/7230591/ENGR481_IR_05_Team_03_mmp.zip)

**Comment by michaeld3951** [comment]
Below is the PPT pdf for IR 05
[ENGR481_IR_05_Presentation_Slides_Team_03.pdf](https://github.com/lydia-wu/cadence/files/7232013/ENGR481_IR_05_Presentation_Slides_Team_03.pdf)

**Comment by htyuki** [comment]
Below is the technical summary and pdf
[ENGR481_IR_05_Technical_Summary_Team_05.docx](https://github.com/lydia-wu/cadence/files/7232405/ENGR481_IR_05_Technical_Summary_Team_05.docx)
[ENGR481_IR_05_Technical_Summary_Team_05.pdf](https://github.com/lydia-wu/cadence/files/7232406/ENGR481_IR_05_Technical_Summary_Team_05.pdf)
:

**Comment by hunter-alloway** [comment]
Good afternoon, I have made revisions to the Technical Summary. Attached are both a .docx as well as a .pdf per the discussion I had with Hayley.
[ENGR481_IR_05_Technical_Summary_Team_05.docx](https://github.com/lydia-wu/cadence/files/7232765/ENGR481_IR_05_Technical_Summary_Team_05.docx)
[ENGR481_IR_05_Technical_Summary_Team_05.pdf](https://github.com/lydia-wu/cadence/files/7232766/ENGR481_IR_05_Technical_Summary_Team_05.pdf)

**Comment by lydia-wu** [comment]
![IR05_confirmation](https://user-images.githubusercontent.com/50425104/134939312-2ba3127b-0339-45ab-9216-b2a5d7b78622.png)

**Comment by michaeld3951** [comment]
Here are the Meeting Minutes for Interim Report 6

[ENGR481_IR_06_Meeting_Minutes_01_Team_03.pdf](https://github.com/lydia-wu/cadence/files/7268968/ENGR481_IR_06_Meeting_Minutes_01_Team_03.pdf)
[ENGR481_IR_06_Meeting_Minutes_02_Team_03.pdf](https://github.com/lydia-wu/cadence/files/7268969/ENGR481_IR_06_Meeting_Minutes_02_Team_03.pdf)

**Comment by lydia-wu** [comment]
[ENGR481_IR_06_Team_03.zip](https://github.com/lydia-wu/cadence/files/7272593/ENGR481_IR_06_Team_03.zip)

no `additional tasking` updates to mpp, but it's good to post for recording purposes

**Comment by htyuki** [comment]
Technical Summary for Interim Report 6:
[ENGR481_IR_06_Technical_Summary_Team_03.docx](https://github.com/lydia-wu/cadence/files/7274122/ENGR481_IR_06_Technical_Summary_Team_03.docx)
[ENGR481_IR_06_Technical_Summary_Team_03.pdf](https://github.com/lydia-wu/cadence/files/7274123/ENGR481_IR_06_Technical_Summary_Team_03.pdf)

**Comment by lydia-wu** [comment]
@michaeld3951 I've had a hiccup on my end, and I don't think Dr. Bae and I will be able to sync up before `IR-06` is due, so just put @hunter-alloway 's current GENESYS diagrams into the `PPT`--

A pic of
- [ ] stakeholder hierarchy diagram just the client (should be able to pull this from DG01 `PPT`)
- [ ] stakeholder hierarchy diagram both client and academic (should be able to pull this from DG01 `PPT`)
- [ ] system req hierarchy diagram, all (should be able to pull this from the latest `.gnux` file directly)

don't worry about formatting or color in the GENSYS pic. 
Here's what @lydia-wu will do once you've got those pics:
- [ ] create some kind of key on the PPT slide, preferably colored-key for each of the _client_ stakeholder reqs, and 1 color for all the academic reqs
- [ ] try to put a color "dot" on each system req

**Comment by lydia-wu** [comment]
I've gotten kicked out of GENESYS with this message, so I'll continue this tomorrow morning--
![sadnessMessage](https://user-images.githubusercontent.com/50425104/135782566-d53a9980-f401-46a2-868b-bfccdcd41459.png)


@michaeld3951 pictures 1/2:

![Client_Stakeholder_Requirements](https://user-images.githubusercontent.com/50425104/135766301-f561fbb8-5036-4675-8d3a-2e2643afbf7a.png)

![Academic_Stakeholder_Requirements](https://user-images.githubusercontent.com/50425104/135766345-1dd7cc3c-5b66-4f4f-b56e-51348bb8d09c.png)

![Stakeholder_Requirements_ALL](https://user-images.githubusercontent.com/50425104/135782322-d9150bf8-aed3-4e76-b1cc-6ca177460072.png)

**Comment by hunter-alloway** [comment]
Just read over the Technical Summary, great work Hayley!

**Comment by michaeld3951** [comment]
@lydia-wu Here are the presentation slides for IR 06
[ENGR481_IR_06_Presentation_Slides_Team_03.pdf](https://github.com/lydia-wu/cadence/files/7278969/ENGR481_IR_06_Presentation_Slides_Team_03.pdf)
[ENGR481_IR_06_Presentation_Slides_Team_03.pptx](https://github.com/lydia-wu/cadence/files/7278970/ENGR481_IR_06_Presentation_Slides_Team_03.pptx)

**Comment by lydia-wu** [comment]
here is the system req diagram--
Doesn't map visually with the stakeholder reqs yet; I will try to indicate that in the PC
![SystemReqFull](https://user-images.githubusercontent.com/50425104/135875576-d9e39fa6-466b-4683-89c1-50f9e668aa54.png)

**Comment by michaeld3951** [comment]
@lydia-wu should I go ahead and edit the ppt with that picture?

**Comment by lydia-wu** [comment]
![image](https://user-images.githubusercontent.com/50425104/135877131-d2e05cd6-a1e6-4438-8ad7-83df9d137dd9.png)

[ENGR481_IR_06_Team_03.zip](https://github.com/lydia-wu/cadence/files/7279104/ENGR481_IR_06_Team_03.zip)

**Comment by hunter-alloway** [comment]
Recap of our previous meeting @htyuki and @michaeld3951 to help with making the Meeting Minutes and Technical Summary.

[Internet of Things-Meeting 10_08_2021.docx](https://github.com/lydia-wu/cadence/files/7313023/Internet.of.Things-Meeting.10_08_2021.docx)

**Comment by lydia-wu** [comment]
I haven't been putting good time into the `.mpp`; here's an updated file that will hopefully help you answer the Monday quiz faster. Should be up to speed with slightly more refined assignments for the immediate future. Take special note of `1.1.3`, `1.1.5`, and `2.1.3`. 

@htyuki @michaeld3951 @hunter-alloway Would you find a proactive, detailed approach to this file valuable? My impression is "no", but that may just be selfishly motivated. I've made an event in my calendar that hopefully will push me to be more proactive about filling this out. I'll continue to burn low on the `.mpp` if it is just superfluous though.

[ENGR481_IR_07_Team_03_mpp.zip](https://github.com/lydia-wu/cadence/files/7317853/ENGR481_IR_07_Team_03_mpp.zip)

**Comment by lydia-wu** [comment]
@htyuki don't worry about updating the Technical Summary; we'll keep this revised `.mpp` for IR-08

**Comment by lydia-wu** [comment]
However, @michaeld3951 can you include the tasking from the latest `.mpp` (IR-07) in the PPT?

**Comment by lydia-wu** [comment]
@hunter-alloway that's great! sounds good

**Comment by michaeld3951** [comment]
Here are the slides for IR 07: 
[ENGR481_IR_07_Presentation_Slides_Team_03.pdf](https://github.com/lydia-wu/cadence/files/7318277/ENGR481_IR_07_Presentation_Slides_Team_03.pdf)
[ENGR481_IR_07_Presentation_Slides_Team_03.pptx](https://github.com/lydia-wu/cadence/files/7318278/ENGR481_IR_07_Presentation_Slides_Team_03.pptx)

**Comment by lydia-wu** [comment]
@hunter-alloway once you've uploaded the modified PPT with your attachment, let me know^
If you get a chance, can you also include the latest System Requirements hierarchy diagram?

**Comment by michaeld3951** [comment]
updated slides:

[ENGR481_IR_07_Presentation_Slides_Team_03.pdf](https://github.com/lydia-wu/cadence/files/7322733/ENGR481_IR_07_Presentation_Slides_Team_03.pdf)
[ENGR481_IR_07_Presentation_Slides_Team_03.pptx](https://github.com/lydia-wu/cadence/files/7322734/ENGR481_IR_07_Presentation_Slides_Team_03.pptx)

**Comment by lydia-wu** [comment]
### Here is the `MS Project`. 
Note changes to:

WBS
--
1.1.6 Discover Architecture
2.1.5.2 Address Decision Gate 05

[ENGR481_IR_09_Team_03_mpp.zip](https://github.com/lydia-wu/cadence/files/7394125/ENGR481_IR_09_Team_03_mpp.zip)

**Comment by hunter-alloway** [comment]
Attached is Interim Report 09, missing the PCM and LRC Upcoming Interim Slides. I included 4 additional slides:

1.   The CADENCE Mission Statement to give everyone a refresher regarding project objective and how we are progressing so far
2.   Two _re-vamped_ Functions Hierarchy slides containing the "bubble-selection" feature per Dr. Bae's request during the pre-decision gate 5 meeting.

3.  Finally I included an example functions-operations mapping that @htyuki per Dr. Bae's request. (Please note that I have included a transition animation to slides 10 and 11 indicated by the small start icon next to the slide. I thought this might induce more engagement with our presentation.)

Please let me know if you have any questions

[ENGR481_IR_09_Presentation_Slides_Team_03.pptx](https://github.com/lydia-wu/cadence/files/7403842/ENGR481_IR_09_Presentation_Slides_Team_03.pptx)

**Comment by michaeld3951** [comment]
Here are the meeting minutes for Interim 10

[ENGR481_IR_10_Meeting_Minutes_01_Team_03.pdf](https://github.com/lydia-wu/cadence/files/7444115/ENGR481_IR_10_Meeting_Minutes_01_Team_03.pdf)
[ENGR481_IR_10_Meeting_Minutes_02_Team_03.pdf](https://github.com/lydia-wu/cadence/files/7444116/ENGR481_IR_10_Meeting_Minutes_02_Team_03.pdf)
[ENGR481_IR_10_Meeting_Minutes_03_Team_03.pdf](https://github.com/lydia-wu/cadence/files/7444117/ENGR481_IR_10_Meeting_Minutes_03_Team_03.pdf)

**Comment by michaeld3951** [comment]
Here's the presentation slides for Interim 10

[ENGR481_IR_10_Presentation_Slides_Team_03.pdf](https://github.com/lydia-wu/cadence/files/7450497/ENGR481_IR_10_Presentation_Slides_Team_03.pdf)
[ENGR481_IR_10_Presentation_Slides_Team_03.pptx](https://github.com/lydia-wu/cadence/files/7450498/ENGR481_IR_10_Presentation_Slides_Team_03.pptx)

**Comment by htyuki** [comment]
Here's the technical summary for Interim 10:
[ENGR481_IR_10_Technical_Summary_Team_03.docx](https://github.com/lydia-wu/cadence/files/7453764/ENGR481_IR_10_Technical_Summary_Team_03.docx)
[ENGR481_IR_10_Technical_Summary_Team_03.pdf](https://github.com/lydia-wu/cadence/files/7453765/ENGR481_IR_10_Technical_Summary_Team_03.pdf)

**Comment by lydia-wu** [comment]
![image](https://user-images.githubusercontent.com/50425104/139697441-9dcc75ad-8cdd-4e66-91d8-0d2b0aa91aa5.png)

[ENGR481_IR_10_Team_03.zip](https://github.com/lydia-wu/cadence/files/7454327/ENGR481_IR_10_Team_03.zip)

**Comment by lydia-wu** [comment]
Great job, team. Closing this for the semester! Woot!
